version: 2.1

orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0


jobs:
  tests:
    docker:
      - image: cimg/python:3.10.7
    steps:
      - checkout # check out the code in the project directory
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Flake8
          command: flake8

  heroku-deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: deploy
          command: |
            HEROKU_API_KEY=$HEROKU_API_KEY heroku config:set SECRET_KEY=$SECRET_KEY --app $HEROKU_APP_NAME
            HEROKU_API_KEY=$HEROKU_API_KEY heroku config:set DSN=$DSN --app $HEROKU_APP_NAME
      - heroku/deploy-via-git

  docker-build:
    docker:
      - image: cimg/python:3.10.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: build
          command: |
            docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
            docker build -t ${DOCKERHUB_USER}/oc_lettings .
            docker push ${DOCKERHUB_USER}/oc_lettings

workflows:
  my-workflow:
    jobs:
      - tests
      - docker-build:
          requires:
            - tests
          filters:
             branches:
              only:
                - main
      - heroku-deploy:
          requires:
            - tests
            - docker-build
          filters:
             branches:
              only:
                - main